AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  Env:
    Type: String
  Project:
    Type: String
    Default: social-doors
  ServiceName:
    Type: String
    Default: facebook

Globals:
  Function:
    Timeout: 900
    Tracing: Active
    Runtime: nodejs22.x
    Architectures:
      - arm64
    Tags:
      project: !Ref Project
      env: !Ref Env
    Environment:
      Variables:
        ENV: !Ref Env

Resources:
  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: true
      QueueName: !Sub ${Project}-${ServiceName}-publish-${Env}-dead-letter.fifo
      Tags:
        - Key: project
          Value: !Ref Project
        - Key: env
          Value: !Ref Env

  PublishQueue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: true
      QueueName: !Sub ${Project}-${ServiceName}-publish-${Env}.fifo
      Tags:
        - Key: project
          Value: !Ref Project
        - Key: env
          Value: !Ref Env
      ContentBasedDeduplication: true
      VisibilityTimeout: 900
      RedrivePolicy:
        deadLetterTargetArn: !Sub ${DeadLetterQueue.Arn}
        maxReceiveCount: 5

  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      FunctionName: !Sub "${Project}-${ServiceName}-publish-${Env}"
      CodeUri: ../publish
      MemorySize: 512
      Environment:
        Variables:
          MONGOOSE_URL: !Sub '{{resolve:ssm:MONGOOSE_URL}}'
          COLLECTION_NAME: !Sub '{{resolve:ssm:COLLECTION_NAME_${Env}}}'
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            BatchSize: 1
            Enabled: true
            Queue: !GetAtt PublishQueue.Arn
            ScalingConfig:
              MaximumConcurrency: 2
      Policies:
        - Statement:
            - Effect: Allow
              Action: s3:GetObject
              Resource: !Sub arn:aws:s3:::social-doors-post-${Env}
